janche:
  # 跨域ip处理
  origins:
    - http://localhost:8080
    - http://192.168.1.202:8080
    - http://127.0.0.1:8080
    - http://cebon.hoteas.com:8082


  #=============日志操作类型==============
  logOperation:
    1: "新增"
    2: "删除"
    3: "修改"
    4: "查看"
    5: "登录"
    6: "退出"
    7: "导出"
    8: "导入"

# 热部署插件指定端口,具体视自己情况而定,只要不重复就可以，默认是35729
spring:
  devtools:
    livereload:
      port: 35730
