cdjcy:
  pagesize: 5
  #  排序属性
  sortcolumn:  "id"
  #  排序规则 1 升序  2 降序
  sorttype: 1
  # 跨域ip处理
  origins: http://localhost:8080,http://192.168.99.100:8091,http://127.0.0.1:8080,http://cebon.hoteas.com:8082
